name: demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.6

  # Dependency Injection
  get_it: ^7.7.0

  # HTTP requests
  http: 1.2.2

  # Functional Programming Utilities (optional)
  dartz: ^0.10.0

  # State Management (if using BLoC)
  flutter_bloc: ^8.0.0

  # For value comparison
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^3.0.0

  # Mocking
  mockito: ^5.0.0

  # Unit Testing utilities
  test: ^1.20.0
